services:
  # PHP service
  php:
    build: ./dockerfiles/php
    container_name: php
    restart: always
    working_dir: /var/www/php
    depends_on:
      - mysql
    volumes:
      - ./projects/myproject:/var/www/php
    networks:
      - ntwk

  # Nginx
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./projects/myproject:/var/www/php
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - ntwk

  # Database
  mysql:
    image: mysql
    container_name: mysql
    environment:
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    networks:
      - ntwk

  # Database manager
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    networks:
      - ntwk
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

networks:
  ntwk:
